---
- name: IIS and other tools are installed
  hosts: win1.example.com
  tasks:

    - name: Install IIS server package
      win_feature:
        name: Web-Server
        state: present

    - name: Install Web-Custom-Logging package
      win_feature:
        name: Web-Custom-Logging
        state: present
    
    - name: Install Web-Log-Libraries package
      win_feature:
        name: Web-Log-Libraries
        state: present
    
    - name: Install Web-Rquest-Monitor package
      win_feature:
        name: Web-Request-Monitor
        state: present
    
    - name: Install Web-Http-Tracing package
      win_feature:
        name: Web-Http-Tracing
        state: present
    
    - name: Install Web-Mgmt-Tools package
      win_feature:
        name: Web-Mgmt-Tools
        state: present

    - name: Server is rebooted
      win_reboot:
